### ISSUE TITLE
Administrator mode for helm-chart

### ISSUE THREAD

**Issue by Jasstkn** [litmuschaos/litmus-helm#10]
I would like to provide cluster wide access for litmus during the HA tests which will be include:
- installation of litmus
- run test
- generate report
- delete litmus.

Could you advice if it's possible to add such option in helm-chart?
I can help with the contribution. Let me know what do you think about that.
thanks!

**Comment by ksatchit** [comment]
Just to share some context around "administrator mode" (we added this term in the litmus lingo recently :) ). There is an SRE centric [admin mode](https://docs.litmuschaos.io/docs/admin-mode/.) supported for Litmus, wherein you could use a single serviceaccount (bound to a clusterrole with wide permissions) in a central ns (could be litmus or any other) to execute different experiments (each exp has a different min. set of requirements needed) -- on apps running across different namespaces. The requirement, other than RBAC, involves creation of the chaosexperiment & chaosengine resources in the same central ns. The experiment pods too run in the same ns.

This is one of the modes of operation in litmus, the other being a more granular/developer-centric approach where the user creates a per-experiment serviceaccount in the namespace where his/her app resides (RBAC manifests are available for each exp, ex: [here](https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/pod-delete/rbac.yaml) ) and also creates the experiment, engine resources here. 

The former is a means to avoid copying resources into several ns repeatedly.

**Comment by Jasstkn** [comment]
Yes, that's what I want to be able configure using helm-chart, but unfortunately rbac example in the docs didn't work for me. I'm going to investigate that later.

**Comment by ksatchit** [comment]
A ref for such rbac is available here: https://github.com/litmuschaos/chaos-helm/tree/master/charts/kubernetes-chaos/templates

**Note about above**: "chaos-helm" is another helm repo which houses the experiment CRs (chart for generic/k8s experiments). It also contains the admin-mode rbac. The reason why this is separate from the litmus-helm repo is because, we wanted litmus-helm to host just the infra components & typically recommend users visit the [chaoshub](hub.litmuschaos.io) over using helm for fetching experiments. And the reason why we placed the admin-mode rbac in chaos-helm is because it is closely connected to experiment execution rather than the orchestration (which is what the operator is associated with). 

Having said the above, if you feel it is better we place the admin-mode rbac here instead, we could do that too.

**Comment by Jasstkn** [comment]
Hm, it's confusing that you don't have single helm-chart repository where user can find litmus infra chart and chart with experiments. Why is that? It's hard to merge all of that in one single picture :(

**Comment by ksatchit** [comment]
Well, that is a good question. Let me try answering that.

**Comment by Jasstkn** [comment]
I spent a lot of time for gathering information. And it's complicated to make it works beside of the demo example in docs.

**Comment by ksatchit** [comment]
you mean via the admin-mode @Jasstkn , or generally using litmus?

**Comment by Jasstkn** [comment]
> you mean via the admin-mode @Jasstkn , or generally using litmus?

Unfortunately, with both of it.

**Comment by ksatchit** [comment]
Ok, we will fix this ASAP and simplify the sore pieces.

**Comment by Jasstkn** [comment]
It would be great! I will working on the monitoring part then. =) Thanks for discussing that with me, highly appreciate.

**Comment by ksatchit** [comment]
> Well, that is a good question. Let me try answering that.

(Disclaimer: The helm support was added recently, in 1.3. So we are still in the initial stages wrt solidifying the user flow. Until now the procedure has been pretty straightforward and  [documented ?](https://docs.litmuschaos.io). So, while we might still end up merging the two charts at the end of this discussion :) wanted to place my thoughts before we decide on anything)

Here are some details: 

Unlike the operator (and going ahead the exporter) which are essentially entities that orchestrate chaos and can be termed "infra" pieces (they have the ability to watch chaosengine CRs across namespaces), the experiments are possible to be used in two modes like we discussed earlier: 

- I. Pulled into specific namespaces by the developer (typically where the app resides). Who then installs the rbac specific to that experiment in the respective ns and proceeds with the creation of a chaosengine (also in the same ns) to trigger the experiment/chaos. This is the standard/general flow. Here is an [example](https://docs.litmuschaos.io/docs/pod-delete/) of this approach. In this example the app is assumed to be in `default` ns.

  The reason why this flow exists is:

  - (A) Often times in situations where multiple developers share a single large cluster (say, staging cluster), they are allocated certain namespaces to operate in. Typically, in such cases the devops admin/owner of the cluster may have setup litmus (via the litmus-helm charts or the operator manifest [here](https://github.com/litmuschaos/pages/blob/master/docs/litmus-operator-v1.3.0.yaml)) and then allow developers to pull desired experiments in their respective ns and run the chaos. They may/may-not have the ability to create cluster-roles or maybe they can but cannot add permissions to certain resources, say. 

  - (B) Now, suppose chaos-experiment templates are also added into the litmus-helm infra chart, a helm install might typically push the exp CRs also into the infra (typically, `litmus`) namespace. Now developers, in case they want to achieve (A), will have to do helm installs such a way that they "omit" operator components and pull only experiments in a given namespace. Which is possible to do, but we need to weigh our options see if we go that way. *In such cases, it may be helpful to have a separate chart only for exp so that people can pull it into the desired ns* 

  - (C) The typical messaging today (when it comes to helm) is to have admin level user install the infra components via litmus-helm & encourage devs to visit the [chaoshub](hub.litmuschaos.io) to pull exp in their namespace, as you might have seen in the docs. Despite keeping the chaos exp in a separate helm repo, we are still not recommending them to use it (not referenced anywhere in docs yet)

- II. (A) The persona here is an SRE (or someone w/ near cluster-admin level, such as a dev with his own dedicated cluster). In this case, the "admin-mode" is brought into effect. Here, the user can install the litmus infra-components (operator, deployment, operator rbac) as well as chaos experiment templates (along with the cluster-wide admin-rbac with ability to run all exp on apps across ns) as part of a single helm install into the same admin ns (typically, `litmus`). 

- II. (B) Today, users are doing (A) via 2 separate actions. Install litmus infra components via litmus-helm & exp via chaos-helm (or from the hub with a `-n litmus` flag to the kubectl apply [command](https://hub.litmuschaos.io/charts/generic)). 

Now, coming to possible solutions for this conundrum, following is my opinion: 

- (a) We could make II.A as a default action. When the admin persona installs litmus he/she gets the infra pieces as well as experiments all placed in to admin/litmus ns. If the same persona is also executing experiments we are already good to go.

- (b) In case there are other non-admin users who execute the experiments, they can continue to do what they have been doing, similar to I.C. Lets not bring helm into the picture here at all. 

This allows to use simplify helm workflow for users as well as keep the hub in picture. We are planning/putting in a considerable bit of work into the hub as it has advantages beyond just install. It is being viewed and positioned as a common interface where users and developers (of experiments) interact, collaborate and visualize their chaos contributions!! 

I hope this makes things a bit clear. Please let us know what you feel about this @Jasstkn ! We are committed to doing whatever it takes to simplify the ease of use of litmus.

**Comment by Jasstkn** [comment]
I clear understand this approach. But, I'm not offering to merge to chart, I just offer to add them in one github repository and add to README their relations and how to use them. Because now it's unclear. And about administrator mode I wanted to implement it as an optional choice instead of default one. Something like that:
administratorMode:
    enabled: true
if this variable is set to true, it will deploy rbac from doc for administrative mode.
In that case it will be a user choice. But those flows should be written in README as well.

**Comment by ksatchit** [comment]
Yes it is a good idea to make it optional. I guess we can get started on that then!

**Comment by Jasstkn** [comment]
Ok, I'll prepare PR then. =)
